### ISSUE TITLE
Failed to execute with private entitlements

### ISSUE THREAD

**Issue by 4ch12dy** [osy86/AMFIExemption#1]
## Environments
macOS: Serra
Lilu kext load success.
AMFIExemption load success.
AMFIExemption info.plist
![image](https://user-images.githubusercontent.com/12497177/146158200-fe197fdc-cf88-46e6-97e5-97dc4540c50d.png)

## Problems
If use self-sign with requested entitlement, the app/cmd will be failed to execute. Terminal just say "zsh: killed"
Console log: `proc 9220: load code signature error 4 for file "snappy"`

I don't understand "This KEXT only disables the requirement that most entitlements require an Apple CA anchor"

AMFIExemption has no " remove amfi check" code , I think. So how to sign binary with private entitlement ? That can get amfi exemption.

**Comment by osy** [comment]
I only tested this on Mojave and Catalina. It probably doesn’t work on other versions.

**Comment by 4ch12dy** [comment]
Thanks for your response!
In Fact, I tested it on Mojave, too.
The problem is below 
> I don't understand "This KEXT only disables the requirement that most entitlements require an Apple CA anchor"

> AMFIExemption has no " remove amfi check" code , I think. So how to sign binary with private entitlement ? That can get amfi exemption.


When I use self-sign with special entitlements, Binary can not execute due to AMFI
![image](https://user-images.githubusercontent.com/12497177/146175201-6fd87a92-e2e5-42ee-bb37-b7f7a3626214.png)



More info:
![image](https://user-images.githubusercontent.com/12497177/146175955-1e1faebf-f735-4a7c-a972-24f13e7bfa84.png)


Could you show more explanation or some examples? Thank you so much!

**Comment by osy** [comment]
Use `codesign -s - --entitlements /path/to/xml /path/to/bin`

**Comment by 4ch12dy** [comment]
> Use `codesign -s - --entitlements /path/to/xml /path/to/bin`
Yes, I use this command to sign it. 
![image](https://user-images.githubusercontent.com/12497177/146355609-1b67709a-8c45-4854-980a-e8ff4d0e48b4.png)
