### ISSUE TITLE
Possible to work on M1 / arm?

### ISSUE THREAD

**Issue by mdbraber** [osy86/AMFIExemption#2]
I'm trying to get this to work on Venture on a Macbook M1. Can AMFIExemption run on a non i386 / x86_64 platform?

**Comment by osy** [comment]
It currently doesn’t work because offsets and symbols have changed since 10.15 and haven’t been updated. Im also not sure if lilu works on arm64.

**Comment by airhorns** [comment]
It seems like someone in this reddit thread was able to get it to work for themselves locally but hasn't shared the code: https://www.reddit.com/r/jailbreakdevelopers/comments/q50mbn/is_it_possible_to_add_entitlement_during_app/ 

Is that enough to go on to add support in the repo proper?
